In [1]:
import torch

In [2]:
m = torch.rand((2, 3))

In [3]:
m

tensor([[0.8470, 0.2915, 0.2645],
        [0.8505, 0.0178, 0.1504]])

In [4]:
m.t()

tensor([[0.8470, 0.8505],
        [0.2915, 0.0178],
        [0.2645, 0.1504]])

In [5]:
torch.einsum("ij->ji", m)

tensor([[0.8470, 0.8505],
        [0.2915, 0.0178],
        [0.2645, 0.1504]])

In [6]:
torch.einsum("ij->j", m)

tensor([1.6975, 0.3093, 0.4149])

In [9]:
torch.einsum("ij->", m)

tensor(2.4217)

In [24]:
v = torch.rand((3, 1))

In [25]:
v

tensor([[0.3063],
        [0.0368],
        [0.2402]])

In [26]:
torch.einsum("ik,kj->ij", m, v)

tensor([[0.3337],
        [0.2972]])

In [27]:
m @ v

tensor([[0.3337],
        [0.2972]])

In [28]:
v = torch.rand((1, 3))

In [29]:
m @ v.t()

tensor([[1.2941],
        [0.9949]])

In [31]:
torch.einsum("ik,jk->ij", m, v)

tensor([[1.2941],
        [0.9949]])

In [38]:
m * m

tensor([[7.1745e-01, 8.4959e-02, 6.9980e-02],
        [7.2328e-01, 3.1745e-04, 2.2624e-02]])

In [46]:
torch.einsum("ii->i", torch.eye(3))

tensor([1., 1., 1.])

In [48]:
a = torch.rand((3,))
b = torch.rand((5,))
torch.einsum("i,j->ij", a, b)

tensor([[0.0306, 0.0575, 0.0101, 0.0452, 0.0585],
        [0.3295, 0.6188, 0.1090, 0.4870, 0.6301],
        [0.4015, 0.7539, 0.1328, 0.5933, 0.7678]])

In [52]:
a.unsqueeze(1) @ b.unsqueeze(0)

tensor([[0.0306, 0.0575, 0.0101, 0.0452, 0.0585],
        [0.3295, 0.6188, 0.1090, 0.4870, 0.6301],
        [0.4015, 0.7539, 0.1328, 0.5933, 0.7678]])

In [53]:
b1 = torch.rand((3, 2, 5))
b2 = torch.rand((3, 5, 3))
torch.einsum("ijk,ikl->ijl", b1, b2)

tensor([[[0.5376, 1.2623, 0.8344],
         [0.4333, 0.9772, 0.4938]],

        [[0.6398, 0.5437, 0.7700],
         [1.8641, 1.5184, 2.1207]],

        [[1.2049, 0.7769, 0.9154],
         [1.1416, 0.9706, 1.5343]]])

In [54]:
torch.einsum("ii->", torch.eye(3))

tensor(3.)